package poll

import (

	"time"

	"gorm.io/datatypes"
)

type PollOption struct {
	ID    string `json:"id"`
	Text  string `json:"text"`
	Count int    `json:"count"`
}

type Poll struct {
	ID        uint                       `json:"id" gorm:"primaryKey"`
	RoomID    string                     `json:"roomId" gorm:"index"`
	PollID    string                     `json:"poll_id" gorm:"uniqueIndex"` // The ID generated by frontend (timestamp)
	Question  string                     `json:"question"`
	Options   datatypes.JSONSlice[PollOption] `json:"options" gorm:"type:json"`
	IsActive  bool                       `json:"isActive"`
	CreatedBy string                     `json:"createdBy"` // Identity of creator
	CreatedAt time.Time                  `json:"createdAt"`
}


